<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Category IDs from DB:
        // 1 => Snekears, 3 => Shoe, 4 => Half Shoe
        // 5 => Ladies shoe, 6 => Ladies Loafer, 7 => Baby Shoe, 8 => Jersey

        $products = [

            // ── Category 1: Snekears ─────────────────────────────────────
            [
                'name'              => 'Nike Air Max 270 Sneakers',
                'description'       => 'The Nike Air Max 270 delivers a bold look with the tallest Air unit in a lifestyle shoe. Its full-length foam midsole provides incredible cushioning for all-day comfort, while the knit upper offers breathability and a secure fit.',
                'short_description' => 'Nike Air Max 270 with tallest Air unit for all-day comfort.',
                'price'             => 2800.00,
                'sale_price'        => 2450.00,
                'SKU'               => 'NIKE-AM270-001',
                'stock'             => 40,
                'status'            => true,
                'category_id'       => 1,
                'sub_category'      => 'Mens Sneakers',
                'brand'             => 'Nike',
                'tax'               => 5.00,
                'discount'          => 12.50,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Nike Air Max 270 Sneakers',
                'meta_description'  => 'Nike Air Max 270 with tallest Air unit for all-day comfort.',
                'meta_keywords'     => 'Nike, Air Max, Sneakers',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Size', 'value' => '43'],
                    ['name' => 'Color', 'value' => 'Black'],
                    ['name' => 'Color', 'value' => 'White'],
                ]),
            ],
            [
                'name'              => 'Adidas Ultraboost 22 Running Sneakers',
                'description'       => 'Adidas Ultraboost 22 offers a responsive BOOST midsole that returns energy with every step. The PRIMEKNIT upper adapts to your foot movement for a sock-like fit. Ideal for running or everyday wear.',
                'short_description' => 'Adidas Ultraboost 22 with BOOST midsole for energy return.',
                'price'             => 3200.00,
                'sale_price'        => 2800.00,
                'SKU'               => 'ADIDAS-UB22-002',
                'stock'             => 25,
                'status'            => true,
                'category_id'       => 1,
                'sub_category'      => 'Mens Sneakers',
                'brand'             => 'Adidas',
                'tax'               => 5.00,
                'discount'          => 12.50,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Adidas Ultraboost 22 Running Sneakers',
                'meta_description'  => 'Adidas Ultraboost 22 with BOOST midsole for energy return.',
                'meta_keywords'     => 'Adidas, Ultraboost, Sneakers',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Color', 'value' => 'Grey'],
                    ['name' => 'Color', 'value' => 'Navy'],
                ]),
            ],
            [
                'name'              => 'Puma RS-X3 Puzzle Sneakers',
                'description'       => 'The Puma RS-X3 Puzzle features an oversized outsole and chunky midsole with RS technology for superior cushioning. Retro-inspired design with modern comfort for streetwear enthusiasts.',
                'short_description' => 'Puma RS-X3 with RS technology and retro-inspired design.',
                'price'             => 2200.00,
                'sale_price'        => 1900.00,
                'SKU'               => 'PUMA-RSX3-003',
                'stock'             => 35,
                'status'            => true,
                'category_id'       => 1,
                'sub_category'      => 'Casual Sneakers',
                'brand'             => 'Puma',
                'tax'               => 5.00,
                'discount'          => 13.64,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Puma RS-X3 Puzzle Sneakers',
                'meta_description'  => 'Puma RS-X3 with RS technology and retro-inspired design.',
                'meta_keywords'     => 'Puma, RS-X3, Sneakers',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Size', 'value' => '44'],
                    ['name' => 'Color', 'value' => 'Red/White'],
                ]),
            ],
            [
                'name'              => 'Reebok Classic Leather Sneakers',
                'description'       => 'The Reebok Classic Leather is an iconic shoe with a clean leather upper and padded sockliner for all-day comfort. A timeless design that works for any casual occasion.',
                'short_description' => 'Reebok Classic Leather – timeless iconic style.',
                'price'             => 1800.00,
                'sale_price'        => 1600.00,
                'SKU'               => 'REEBOK-CL-004',
                'stock'             => 50,
                'status'            => true,
                'category_id'       => 1,
                'sub_category'      => 'Casual Sneakers',
                'brand'             => 'Reebok',
                'tax'               => 5.00,
                'discount'          => 11.11,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Reebok Classic Leather Sneakers',
                'meta_description'  => 'Reebok Classic Leather – timeless iconic style.',
                'meta_keywords'     => 'Reebok, Classic, Sneakers',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '39'],
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Color', 'value' => 'White'],
                    ['name' => 'Color', 'value' => 'Chalk'],
                ]),
            ],
            [
                'name'              => 'Converse Chuck Taylor All Star Sneakers',
                'description'       => 'The Converse Chuck Taylor All Star is a cultural icon with a canvas upper, rubber sole, and OrthoLite insole. A versatile sneaker perfect for every generation and style.',
                'short_description' => 'Converse Chuck Taylor – a cultural sneaker icon.',
                'price'             => 1600.00,
                'sale_price'        => 1400.00,
                'SKU'               => 'CONV-CT-005',
                'stock'             => 60,
                'status'            => true,
                'category_id'       => 1,
                'sub_category'      => 'Casual Sneakers',
                'brand'             => 'Converse',
                'tax'               => 5.00,
                'discount'          => 12.50,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Converse Chuck Taylor All Star Sneakers',
                'meta_description'  => 'Converse Chuck Taylor – a cultural sneaker icon.',
                'meta_keywords'     => 'Converse, Chuck Taylor, Sneakers',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Color', 'value' => 'Black'],
                    ['name' => 'Color', 'value' => 'Optical White'],
                ]),
            ],

            // ── Category 3: Shoe ─────────────────────────────────────────
            [
                'name'              => 'Oxford Brogue Formal Shoe',
                'description'       => 'A classic Oxford brogue crafted from genuine leather with hand-stitched detailing and a cushioned leather insole. Perfect for business meetings, formal events, and everyday office wear.',
                'short_description' => 'Classic Oxford Brogue in genuine leather for formal occasions.',
                'price'             => 2500.00,
                'sale_price'        => 2200.00,
                'SKU'               => 'APEX-OXF-006',
                'stock'             => 20,
                'status'            => true,
                'category_id'       => 3,
                'sub_category'      => 'Mens Formal',
                'brand'             => 'Apex',
                'tax'               => 10.00,
                'discount'          => 12.00,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Oxford Brogue Formal Shoe',
                'meta_description'  => 'Classic Oxford Brogue in genuine leather for formal occasions.',
                'meta_keywords'     => 'Oxford, Brogue, Formal Shoe',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Size', 'value' => '43'],
                    ['name' => 'Color', 'value' => 'Brown'],
                    ['name' => 'Color', 'value' => 'Black'],
                ]),
            ],
            [
                'name'              => 'Derby Lace-Up Business Shoe',
                'description'       => 'The Derby lace-up shoe features an open-lacing system and smooth leather upper for a polished professional look. Durable rubber sole with excellent grip and a soft padded collar for comfort.',
                'short_description' => 'Derby lace-up with open-lacing for a polished business look.',
                'price'             => 2100.00,
                'sale_price'        => 1900.00,
                'SKU'               => 'BATA-DLB-007',
                'stock'             => 30,
                'status'            => true,
                'category_id'       => 3,
                'sub_category'      => 'Mens Formal',
                'brand'             => 'Bata',
                'tax'               => 10.00,
                'discount'          => 9.52,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Derby Lace-Up Business Shoe',
                'meta_description'  => 'Derby lace-up with open-lacing for a polished business look.',
                'meta_keywords'     => 'Derby, Business Shoe, Formal',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Size', 'value' => '44'],
                    ['name' => 'Color', 'value' => 'Black'],
                ]),
            ],
            [
                'name'              => 'Monk Strap Leather Dress Shoe',
                'description'       => 'Single monk-strap design with a sleek leather upper and metallic buckle closure. Provides a sophisticated and contemporary look suited for weddings, parties, and formal gatherings.',
                'short_description' => 'Single monk-strap leather dress shoe for sophisticated occasions.',
                'price'             => 2600.00,
                'sale_price'        => 2350.00,
                'SKU'               => 'APEX-MKS-008',
                'stock'             => 15,
                'status'            => true,
                'category_id'       => 3,
                'sub_category'      => 'Mens Formal',
                'brand'             => 'Apex',
                'tax'               => 10.00,
                'discount'          => 9.62,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Monk Strap Leather Dress Shoe',
                'meta_description'  => 'Single monk-strap leather dress shoe for sophisticated occasions.',
                'meta_keywords'     => 'Monk Strap, Dress Shoe, Leather',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Size', 'value' => '43'],
                    ['name' => 'Color', 'value' => 'Tan'],
                    ['name' => 'Color', 'value' => 'Black'],
                ]),
            ],
            [
                'name'              => 'Chelsea Boot Casual Shoe',
                'description'       => 'Sleek Chelsea boot with elastic side panels and a pull tab for easy wear. Made from premium leather with a low block heel and rubber outsole for everyday durability.',
                'short_description' => 'Chelsea boot with elastic panels and low block heel.',
                'price'             => 2900.00,
                'sale_price'        => 2600.00,
                'SKU'               => 'BATA-CLB-009',
                'stock'             => 18,
                'status'            => true,
                'category_id'       => 3,
                'sub_category'      => 'Mens Casual',
                'brand'             => 'Bata',
                'tax'               => 10.00,
                'discount'          => 10.34,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Chelsea Boot Casual Shoe',
                'meta_description'  => 'Chelsea boot with elastic panels and low block heel.',
                'meta_keywords'     => 'Chelsea Boot, Casual Shoe',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Size', 'value' => '43'],
                    ['name' => 'Color', 'value' => 'Dark Brown'],
                    ['name' => 'Color', 'value' => 'Black'],
                ]),
            ],
            [
                'name'              => 'Loafer Penny Slip-On Shoe',
                'description'       => 'The penny loafer is a wardrobe essential with a moccasin construction and decorative strap. Crafted from soft calf leather with a flexible rubber sole – perfect for casual Friday or relaxed weekends.',
                'short_description' => 'Penny loafer in soft calf leather – casual wardrobe essential.',
                'price'             => 1950.00,
                'sale_price'        => 1750.00,
                'SKU'               => 'CLARKS-PL-010',
                'stock'             => 22,
                'status'            => true,
                'category_id'       => 3,
                'sub_category'      => 'Mens Casual',
                'brand'             => 'Clarks',
                'tax'               => 10.00,
                'discount'          => 10.26,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Loafer Penny Slip-On Shoe',
                'meta_description'  => 'Penny loafer in soft calf leather – casual wardrobe essential.',
                'meta_keywords'     => 'Loafer, Penny, Slip-On',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Color', 'value' => 'Tan'],
                    ['name' => 'Color', 'value' => 'Cognac'],
                ]),
            ],

            // ── Category 4: Half Shoe ─────────────────────────────────────
            [
                'name'              => 'Men\'s Leather Half Shoe Classic',
                'description'       => 'A refined half-shoe silhouette in genuine cowhide leather with a breathable mesh lining. The lightweight EVA outsole ensures comfort throughout the day, making it ideal for both office and evening use.',
                'short_description' => 'Genuine cowhide leather half shoe with EVA outsole.',
                'price'             => 1700.00,
                'sale_price'        => 1550.00,
                'SKU'               => 'APEX-MHS-011',
                'stock'             => 28,
                'status'            => true,
                'category_id'       => 4,
                'sub_category'      => 'Mens Half Shoe',
                'brand'             => 'Apex',
                'tax'               => 8.00,
                'discount'          => 8.82,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Men\'s Leather Half Shoe Classic',
                'meta_description'  => 'Genuine cowhide leather half shoe with EVA outsole.',
                'meta_keywords'     => 'Half Shoe, Leather, Mens',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Color', 'value' => 'Black'],
                    ['name' => 'Color', 'value' => 'Dark Brown'],
                ]),
            ],
            [
                'name'              => 'Slip-On Canvas Half Shoe',
                'description'       => 'A relaxed slip-on half shoe made from durable canvas with a vulcanized rubber sole. Lightweight and breathable, perfect for summer outings, beach days, or casual walks.',
                'short_description' => 'Canvas slip-on half shoe – lightweight and breathable.',
                'price'             => 900.00,
                'sale_price'        => 790.00,
                'SKU'               => 'BATA-SOCH-012',
                'stock'             => 45,
                'status'            => true,
                'category_id'       => 4,
                'sub_category'      => 'Mens Half Shoe',
                'brand'             => 'Bata',
                'tax'               => 5.00,
                'discount'          => 12.22,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Slip-On Canvas Half Shoe',
                'meta_description'  => 'Canvas slip-on half shoe – lightweight and breathable.',
                'meta_keywords'     => 'Canvas, Slip-On, Half Shoe',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '39'],
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Color', 'value' => 'Navy'],
                    ['name' => 'Color', 'value' => 'Grey'],
                ]),
            ],
            [
                'name'              => 'Elastic Gusset Comfort Half Shoe',
                'description'       => 'Features a dual elastic gusset for easy on/off and a memory foam footbed for superior comfort. Suede upper with a flexible rubber sole – great for seniors or anyone who values easy-wear shoes.',
                'short_description' => 'Dual elastic gusset half shoe with memory foam footbed.',
                'price'             => 1200.00,
                'sale_price'        => 1050.00,
                'SKU'               => 'CLARKS-EGHS-013',
                'stock'             => 32,
                'status'            => true,
                'category_id'       => 4,
                'sub_category'      => 'Comfort Half Shoe',
                'brand'             => 'Clarks',
                'tax'               => 5.00,
                'discount'          => 12.50,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Elastic Gusset Comfort Half Shoe',
                'meta_description'  => 'Dual elastic gusset half shoe with memory foam footbed.',
                'meta_keywords'     => 'Comfort, Half Shoe, Elastic',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Size', 'value' => '44'],
                    ['name' => 'Color', 'value' => 'Beige'],
                    ['name' => 'Color', 'value' => 'Brown'],
                ]),
            ],
            [
                'name'              => 'Sport Mesh Breathable Half Shoe',
                'description'       => 'Engineered mesh upper for maximum ventilation combined with a cushioned EVA insole. Ideal for light workouts, walks, or everyday casual wear throughout warm seasons.',
                'short_description' => 'Mesh breathable half shoe with cushioned EVA insole.',
                'price'             => 1100.00,
                'sale_price'        => 950.00,
                'SKU'               => 'PUMA-SMBH-014',
                'stock'             => 38,
                'status'            => true,
                'category_id'       => 4,
                'sub_category'      => 'Sport Half Shoe',
                'brand'             => 'Puma',
                'tax'               => 5.00,
                'discount'          => 13.64,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Sport Mesh Breathable Half Shoe',
                'meta_description'  => 'Mesh breathable half shoe with cushioned EVA insole.',
                'meta_keywords'     => 'Sport, Mesh, Half Shoe',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Color', 'value' => 'Blue'],
                    ['name' => 'Color', 'value' => 'Red'],
                ]),
            ],
            [
                'name'              => 'Buckle Strap Formal Half Shoe',
                'description'       => 'Smart formal half shoe with a single adjustable buckle strap and a polished leather upper. Rubber outsole with non-slip grip, suitable for rainy seasons and slippery floors.',
                'short_description' => 'Buckle strap formal half shoe with non-slip rubber outsole.',
                'price'             => 1500.00,
                'sale_price'        => 1350.00,
                'SKU'               => 'APEX-BSFH-015',
                'stock'             => 20,
                'status'            => true,
                'category_id'       => 4,
                'sub_category'      => 'Mens Half Shoe',
                'brand'             => 'Apex',
                'tax'               => 8.00,
                'discount'          => 10.00,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Buckle Strap Formal Half Shoe',
                'meta_description'  => 'Buckle strap formal half shoe with non-slip rubber outsole.',
                'meta_keywords'     => 'Buckle Strap, Formal, Half Shoe',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '40'],
                    ['name' => 'Size', 'value' => '41'],
                    ['name' => 'Size', 'value' => '42'],
                    ['name' => 'Color', 'value' => 'Black'],
                    ['name' => 'Color', 'value' => 'Burgundy'],
                ]),
            ],

            // ── Category 5: Ladies Shoe ──────────────────────────────────
            [
                'name'              => 'Ladies Classic Stiletto Heel Pump',
                'description'       => 'An elegant stiletto heel pump in premium patent leather with a pointed toe and slim 10cm heel. Perfect for weddings, parties, and formal events. Available in a range of sophisticated colours.',
                'short_description' => 'Patent leather stiletto pump with slim 10cm heel.',
                'price'             => 1800.00,
                'sale_price'        => 1600.00,
                'SKU'               => 'BATA-LSHS-016',
                'stock'             => 30,
                'status'            => true,
                'category_id'       => 5,
                'sub_category'      => 'Heels',
                'brand'             => 'Bata',
                'tax'               => 5.00,
                'discount'          => 11.11,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Ladies Classic Stiletto Heel Pump',
                'meta_description'  => 'Patent leather stiletto pump with slim 10cm heel.',
                'meta_keywords'     => 'Stiletto, Heels, Ladies Shoe',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '36'],
                    ['name' => 'Size', 'value' => '37'],
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Size', 'value' => '39'],
                    ['name' => 'Color', 'value' => 'Nude'],
                    ['name' => 'Color', 'value' => 'Black'],
                    ['name' => 'Color', 'value' => 'Red'],
                ]),
            ],
            [
                'name'              => 'Women\'s Flat Ballerina Shoe',
                'description'       => 'A comfortable flat ballerina with a soft fabric upper and flexible sole. Features an elasticated topline for a secure fit and a lightly padded insole for all-day comfort.',
                'short_description' => 'Soft flat ballerina with elasticated topline for comfort.',
                'price'             => 1100.00,
                'sale_price'        => 950.00,
                'SKU'               => 'APEX-LFBS-017',
                'stock'             => 45,
                'status'            => true,
                'category_id'       => 5,
                'sub_category'      => 'Flats',
                'brand'             => 'Apex',
                'tax'               => 5.00,
                'discount'          => 13.64,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Women\'s Flat Ballerina Shoe',
                'meta_description'  => 'Soft flat ballerina with elasticated topline for comfort.',
                'meta_keywords'     => 'Ballerina, Flat, Ladies Shoe',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '36'],
                    ['name' => 'Size', 'value' => '37'],
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Color', 'value' => 'Pink'],
                    ['name' => 'Color', 'value' => 'Ivory'],
                ]),
            ],
            [
                'name'              => 'Block Heel Ankle Strap Sandal Shoe',
                'description'       => 'Chic block heel sandal with an adjustable ankle strap for stability and a cushioned footbed for comfort. Versatile design that transitions from daytime casual to evening elegance.',
                'short_description' => 'Block heel sandal with ankle strap – day to evening style.',
                'price'             => 1500.00,
                'sale_price'        => 1300.00,
                'SKU'               => 'BATA-BHSS-018',
                'stock'             => 25,
                'status'            => true,
                'category_id'       => 5,
                'sub_category'      => 'Sandals',
                'brand'             => 'Bata',
                'tax'               => 5.00,
                'discount'          => 13.33,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Block Heel Ankle Strap Sandal Shoe',
                'meta_description'  => 'Block heel sandal with ankle strap – day to evening style.',
                'meta_keywords'     => 'Block Heel, Sandal, Ladies Shoe',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '36'],
                    ['name' => 'Size', 'value' => '37'],
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Size', 'value' => '39'],
                    ['name' => 'Color', 'value' => 'Camel'],
                    ['name' => 'Color', 'value' => 'Black'],
                ]),
            ],
            [
                'name'              => 'Ladies Platform Wedge Shoe',
                'description'       => 'Platform wedge shoe with espadrille-inspired sole and a zip closure at the back. Provides extra height without sacrificing comfort, ideal for summer outings and casual brunches.',
                'short_description' => 'Platform wedge with espadrille sole and back zip closure.',
                'price'             => 1600.00,
                'sale_price'        => 1400.00,
                'SKU'               => 'APEX-LPWS-019',
                'stock'             => 20,
                'status'            => true,
                'category_id'       => 5,
                'sub_category'      => 'Wedges',
                'brand'             => 'Apex',
                'tax'               => 5.00,
                'discount'          => 12.50,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Ladies Platform Wedge Shoe',
                'meta_description'  => 'Platform wedge with espadrille sole and back zip closure.',
                'meta_keywords'     => 'Wedge, Platform, Ladies Shoe',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '36'],
                    ['name' => 'Size', 'value' => '37'],
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Color', 'value' => 'Beige'],
                    ['name' => 'Color', 'value' => 'White'],
                ]),
            ],
            [
                'name'              => 'Women\'s Mule Slip-On Clog Shoe',
                'description'       => 'Trendy mule clog with a cork-inspired wedge platform and a wide front strap. Easy slip-on design with a contoured footbed for relaxed everyday comfort.',
                'short_description' => 'Cork-wedge mule clog with contoured footbed.',
                'price'             => 1250.00,
                'sale_price'        => 1100.00,
                'SKU'               => 'BATA-WMSC-020',
                'stock'             => 35,
                'status'            => true,
                'category_id'       => 5,
                'sub_category'      => 'Mules',
                'brand'             => 'Bata',
                'tax'               => 5.00,
                'discount'          => 12.00,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Women\'s Mule Slip-On Clog Shoe',
                'meta_description'  => 'Cork-wedge mule clog with contoured footbed.',
                'meta_keywords'     => 'Mule, Clog, Ladies Shoe',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '36'],
                    ['name' => 'Size', 'value' => '37'],
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Color', 'value' => 'Natural Cork'],
                    ['name' => 'Color', 'value' => 'Black'],
                ]),
            ],

            // ── Category 6: Ladies Loafer ─────────────────────────────────
            [
                'name'              => 'Women\'s Suede Penny Loafer',
                'description'       => 'Classic suede penny loafer with a strap detail and a cushioned leather insole. Slip-on design with a low heel and flexible rubber outsole for effortless style and comfort.',
                'short_description' => 'Classic suede penny loafer with cushioned leather insole.',
                'price'             => 1400.00,
                'sale_price'        => 1250.00,
                'SKU'               => 'CLARKS-WSPL-021',
                'stock'             => 30,
                'status'            => true,
                'category_id'       => 6,
                'sub_category'      => 'Loafer',
                'brand'             => 'Clarks',
                'tax'               => 5.00,
                'discount'          => 10.71,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Women\'s Suede Penny Loafer',
                'meta_description'  => 'Classic suede penny loafer with cushioned leather insole.',
                'meta_keywords'     => 'Suede, Penny Loafer, Ladies',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '36'],
                    ['name' => 'Size', 'value' => '37'],
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Color', 'value' => 'Caramel'],
                    ['name' => 'Color', 'value' => 'Black'],
                ]),
            ],
            [
                'name'              => 'Ladies Tassel Loafer',
                'description'       => 'Smart tassel loafer in smooth leather with decorative tassel detail on the vamp. Features a low stacked heel and a leather lining for breathability – versatile for workwear or weekend style.',
                'short_description' => 'Leather tassel loafer with low stacked heel.',
                'price'             => 1600.00,
                'sale_price'        => 1420.00,
                'SKU'               => 'APEX-LTLF-022',
                'stock'             => 25,
                'status'            => true,
                'category_id'       => 6,
                'sub_category'      => 'Loafer',
                'brand'             => 'Apex',
                'tax'               => 5.00,
                'discount'          => 11.25,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Ladies Tassel Loafer',
                'meta_description'  => 'Leather tassel loafer with low stacked heel.',
                'meta_keywords'     => 'Tassel, Loafer, Ladies',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '36'],
                    ['name' => 'Size', 'value' => '37'],
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Color', 'value' => 'Chocolate'],
                    ['name' => 'Color', 'value' => 'Black'],
                ]),
            ],
            [
                'name'              => 'Platform Loafer with Lug Sole',
                'description'       => 'Bold chunky platform loafer with a thick lug rubber sole for a contemporary look. Leather upper with metal chain embellishment for an edgy, fashionable statement.',
                'short_description' => 'Chunky platform loafer with lug sole and chain detail.',
                'price'             => 1900.00,
                'sale_price'        => 1700.00,
                'SKU'               => 'BATA-PLLS-023',
                'stock'             => 18,
                'status'            => true,
                'category_id'       => 6,
                'sub_category'      => 'Platform Loafer',
                'brand'             => 'Bata',
                'tax'               => 5.00,
                'discount'          => 10.53,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Platform Loafer with Lug Sole',
                'meta_description'  => 'Chunky platform loafer with lug sole and chain detail.',
                'meta_keywords'     => 'Platform Loafer, Lug Sole, Ladies',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '36'],
                    ['name' => 'Size', 'value' => '37'],
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Size', 'value' => '39'],
                    ['name' => 'Color', 'value' => 'Black'],
                    ['name' => 'Color', 'value' => 'White'],
                ]),
            ],
            [
                'name'              => 'Velvet Horsebit Loafer',
                'description'       => 'Luxurious velvet loafer with a gold-tone horsebit embellishment. Smooth leather insole and rubber sole. Adds a touch of luxury to any evening or smart-casual outfit.',
                'short_description' => 'Velvet loafer with gold horsebit embellishment.',
                'price'             => 2200.00,
                'sale_price'        => 1980.00,
                'SKU'               => 'CLARKS-VHL-024',
                'stock'             => 12,
                'status'            => true,
                'category_id'       => 6,
                'sub_category'      => 'Loafer',
                'brand'             => 'Clarks',
                'tax'               => 5.00,
                'discount'          => 10.00,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Velvet Horsebit Loafer',
                'meta_description'  => 'Velvet loafer with gold horsebit embellishment.',
                'meta_keywords'     => 'Velvet, Horsebit, Loafer',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '36'],
                    ['name' => 'Size', 'value' => '37'],
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Color', 'value' => 'Emerald Green'],
                    ['name' => 'Color', 'value' => 'Midnight Navy'],
                ]),
            ],
            [
                'name'              => 'Moccasin Driving Loafer',
                'description'       => 'Soft moccasin-stitch driving loafer with rubber pebble sole for grip and flexibility. Ideal for everyday driving or light casual wear, featuring a genuine leather upper.',
                'short_description' => 'Moccasin driving loafer with pebble rubber sole.',
                'price'             => 1300.00,
                'sale_price'        => 1150.00,
                'SKU'               => 'APEX-MDL-025',
                'stock'             => 22,
                'status'            => true,
                'category_id'       => 6,
                'sub_category'      => 'Driving Loafer',
                'brand'             => 'Apex',
                'tax'               => 5.00,
                'discount'          => 11.54,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Moccasin Driving Loafer',
                'meta_description'  => 'Moccasin driving loafer with pebble rubber sole.',
                'meta_keywords'     => 'Moccasin, Driving, Loafer',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '36'],
                    ['name' => 'Size', 'value' => '37'],
                    ['name' => 'Size', 'value' => '38'],
                    ['name' => 'Color', 'value' => 'Tan'],
                    ['name' => 'Color', 'value' => 'Dark Brown'],
                ]),
            ],

            // ── Category 7: Baby Shoe ─────────────────────────────────────
            [
                'name'              => 'Toddler First Step Soft Sole Shoe',
                'description'       => 'Designed for babies taking their first steps, this soft-sole shoe features a flexible suede outsole and breathable mesh upper. Anti-slip sole and velcro closure for easy on/off.',
                'short_description' => 'Baby first step shoe with soft suede sole and velcro.',
                'price'             => 650.00,
                'sale_price'        => 550.00,
                'SKU'               => 'BABY-FSSB-026',
                'stock'             => 60,
                'status'            => true,
                'category_id'       => 7,
                'sub_category'      => 'Infant Shoes',
                'brand'             => 'BabyStep',
                'tax'               => 0.00,
                'discount'          => 15.38,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Toddler First Step Soft Sole Shoe',
                'meta_description'  => 'Baby first step shoe with soft suede sole and velcro.',
                'meta_keywords'     => 'Baby Shoe, First Step, Toddler',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '16'],
                    ['name' => 'Size', 'value' => '17'],
                    ['name' => 'Size', 'value' => '18'],
                    ['name' => 'Size', 'value' => '19'],
                    ['name' => 'Color', 'value' => 'Pink'],
                    ['name' => 'Color', 'value' => 'Blue'],
                ]),
            ],
            [
                'name'              => 'Kids Cartoon Character Sneaker',
                'description'       => 'Fun and colourful cartoon character sneaker with flashing LED lights. Lightweight EVA sole, breathable mesh upper, and easy velcro strap closure – kids will love them!',
                'short_description' => 'LED flashing cartoon sneaker with velcro strap for kids.',
                'price'             => 850.00,
                'sale_price'        => 750.00,
                'SKU'               => 'BABY-KCSN-027',
                'stock'             => 50,
                'status'            => true,
                'category_id'       => 7,
                'sub_category'      => 'Kids Sneakers',
                'brand'             => 'BabyStep',
                'tax'               => 0.00,
                'discount'          => 11.76,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Kids Cartoon Character Sneaker',
                'meta_description'  => 'LED flashing cartoon sneaker with velcro strap for kids.',
                'meta_keywords'     => 'Kids Sneaker, LED, Cartoon',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '20'],
                    ['name' => 'Size', 'value' => '21'],
                    ['name' => 'Size', 'value' => '22'],
                    ['name' => 'Size', 'value' => '23'],
                    ['name' => 'Color', 'value' => 'Red'],
                    ['name' => 'Color', 'value' => 'Blue'],
                ]),
            ],
            [
                'name'              => 'Baby Sandal with Ankle Support',
                'description'       => 'Ergonomic baby sandal with adjustable ankle strap for proper support and natural foot development. PU leather upper with anti-slip outsole and cushioned footbed.',
                'short_description' => 'Ergonomic baby sandal with adjustable ankle strap.',
                'price'             => 700.00,
                'sale_price'        => 620.00,
                'SKU'               => 'BABY-SAS-028',
                'stock'             => 40,
                'status'            => true,
                'category_id'       => 7,
                'sub_category'      => 'Infant Sandals',
                'brand'             => 'TinyFeet',
                'tax'               => 0.00,
                'discount'          => 11.43,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Baby Sandal with Ankle Support',
                'meta_description'  => 'Ergonomic baby sandal with adjustable ankle strap.',
                'meta_keywords'     => 'Baby Sandal, Ankle Support, Toddler',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '18'],
                    ['name' => 'Size', 'value' => '19'],
                    ['name' => 'Size', 'value' => '20'],
                    ['name' => 'Color', 'value' => 'Yellow'],
                    ['name' => 'Color', 'value' => 'White'],
                ]),
            ],
            [
                'name'              => 'Children\'s School Shoe',
                'description'       => 'Durable school shoe with a T-bar strap, scuff-resistant toe cap, and cushioned insole. Engineered to withstand active school days while keeping feet comfortable and supported.',
                'short_description' => 'Durable T-bar school shoe with scuff-resistant toe cap.',
                'price'             => 950.00,
                'sale_price'        => 850.00,
                'SKU'               => 'BATA-CSS-029',
                'stock'             => 55,
                'status'            => true,
                'category_id'       => 7,
                'sub_category'      => 'School Shoes',
                'brand'             => 'Bata',
                'tax'               => 0.00,
                'discount'          => 10.53,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Children\'s School Shoe',
                'meta_description'  => 'Durable T-bar school shoe with scuff-resistant toe cap.',
                'meta_keywords'     => 'School Shoe, Children, Kids',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '28'],
                    ['name' => 'Size', 'value' => '30'],
                    ['name' => 'Size', 'value' => '32'],
                    ['name' => 'Size', 'value' => '34'],
                    ['name' => 'Color', 'value' => 'Black'],
                ]),
            ],
            [
                'name'              => 'Baby Slip-On Crib Bootie',
                'description'       => 'Adorable soft crib bootie for newborns and infants. Made from 100% organic cotton with a gentle elasticised opening for easy fit. Machine washable and skin-safe.',
                'short_description' => 'Organic cotton crib bootie for newborns – machine washable.',
                'price'             => 450.00,
                'sale_price'        => 390.00,
                'SKU'               => 'TINY-SCB-030',
                'stock'             => 80,
                'status'            => true,
                'category_id'       => 7,
                'sub_category'      => 'Crib Shoes',
                'brand'             => 'TinyFeet',
                'tax'               => 0.00,
                'discount'          => 13.33,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => false,
                'organic'           => true,
                'new_arrival'       => true,
                'meta_title'        => 'Baby Slip-On Crib Bootie',
                'meta_description'  => 'Organic cotton crib bootie for newborns – machine washable.',
                'meta_keywords'     => 'Crib Bootie, Baby, Newborn',
                'attributes'        => json_encode([
                    ['name' => 'Size', 'value' => '14'],
                    ['name' => 'Size', 'value' => '15'],
                    ['name' => 'Size', 'value' => '16'],
                    ['name' => 'Color', 'value' => 'Cream'],
                    ['name' => 'Color', 'value' => 'Mint Green'],
                ]),
            ],

            // ── Category 8: Jersey ────────────────────────────────────────
            [
                'name'              => 'Argentina Home Jersey 2026',
                'description'       => 'Official fan-version Argentina 2026 World Cup home jersey featuring the classic sky-blue and white vertical stripes. Lightweight moisture-wicking fabric with embroidered AFA crest and three stars.',
                'short_description' => 'Argentina 2026 home jersey with AFA crest and three stars.',
                'price'             => 1350.00,
                'sale_price'        => 1150.00,
                'SKU'               => 'ADIDAS-ARG-031',
                'stock'             => 40,
                'status'            => true,
                'category_id'       => 8,
                'sub_category'      => 'Football Jersey',
                'brand'             => 'Adidas',
                'tax'               => 10.00,
                'discount'          => 14.81,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'Argentina Home Jersey 2026',
                'meta_description'  => 'Argentina 2026 home jersey with AFA crest and three stars.',
                'meta_keywords'     => 'Argentina, Football Jersey, 2026',
                'attributes'        => json_encode([
                    ['name' => 'Dress Size', 'value' => 'S'],
                    ['name' => 'Dress Size', 'value' => 'M'],
                    ['name' => 'Dress Size', 'value' => 'L'],
                    ['name' => 'Dress Size', 'value' => 'XL'],
                    ['name' => 'Dress Size', 'value' => 'XXL'],
                    ['name' => 'Color', 'value' => 'Sky Blue/White'],
                ]),
            ],
            [
                'name'              => 'England Away Jersey 2026',
                'description'       => 'England 2026 away jersey in a sleek dark navy colourway with the Three Lions crest embroidered on the chest. Breathable ClimaChill technology for peak performance on and off the pitch.',
                'short_description' => 'England 2026 away jersey in navy with Three Lions crest.',
                'price'             => 1250.00,
                'sale_price'        => 1050.00,
                'SKU'               => 'NIKE-ENG-032',
                'stock'             => 35,
                'status'            => true,
                'category_id'       => 8,
                'sub_category'      => 'Football Jersey',
                'brand'             => 'Nike',
                'tax'               => 10.00,
                'discount'          => 16.00,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'England Away Jersey 2026',
                'meta_description'  => 'England 2026 away jersey in navy with Three Lions crest.',
                'meta_keywords'     => 'England, Football Jersey, 2026',
                'attributes'        => json_encode([
                    ['name' => 'Dress Size', 'value' => 'S'],
                    ['name' => 'Dress Size', 'value' => 'M'],
                    ['name' => 'Dress Size', 'value' => 'L'],
                    ['name' => 'Dress Size', 'value' => 'XL'],
                    ['name' => 'Color', 'value' => 'Navy'],
                ]),
            ],
            [
                'name'              => 'Germany Home Jersey 2026',
                'description'       => 'Iconic Germany 2026 home jersey in classic white with black trim and the DFB eagle crest. Made from recycled polyester fabric to promote sustainability without compromising performance.',
                'short_description' => 'Germany 2026 home jersey in white with DFB eagle crest.',
                'price'             => 1200.00,
                'sale_price'        => 1000.00,
                'SKU'               => 'ADIDAS-GER-033',
                'stock'             => 30,
                'status'            => true,
                'category_id'       => 8,
                'sub_category'      => 'Football Jersey',
                'brand'             => 'Adidas',
                'tax'               => 10.00,
                'discount'          => 16.67,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => true,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Germany Home Jersey 2026',
                'meta_description'  => 'Germany 2026 home jersey in white with DFB eagle crest.',
                'meta_keywords'     => 'Germany, Football Jersey, 2026',
                'attributes'        => json_encode([
                    ['name' => 'Dress Size', 'value' => 'S'],
                    ['name' => 'Dress Size', 'value' => 'M'],
                    ['name' => 'Dress Size', 'value' => 'L'],
                    ['name' => 'Dress Size', 'value' => 'XL'],
                    ['name' => 'Dress Size', 'value' => 'XXL'],
                    ['name' => 'Color', 'value' => 'White'],
                ]),
            ],
            [
                'name'              => 'Spain Home Jersey 2026',
                'description'       => 'Spain 2026 home jersey in vibrant red with the RFEF badge and golden accents. Slim-fit silhouette with AeroSwift technology for freedom of movement during intense gameplay.',
                'short_description' => 'Spain 2026 home jersey in red with RFEF badge.',
                'price'             => 1300.00,
                'sale_price'        => 1100.00,
                'SKU'               => 'NIKE-ESP-034',
                'stock'             => 28,
                'status'            => true,
                'category_id'       => 8,
                'sub_category'      => 'Football Jersey',
                'brand'             => 'Nike',
                'tax'               => 10.00,
                'discount'          => 15.38,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => true,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => false,
                'meta_title'        => 'Spain Home Jersey 2026',
                'meta_description'  => 'Spain 2026 home jersey in red with RFEF badge.',
                'meta_keywords'     => 'Spain, Football Jersey, 2026',
                'attributes'        => json_encode([
                    ['name' => 'Dress Size', 'value' => 'S'],
                    ['name' => 'Dress Size', 'value' => 'M'],
                    ['name' => 'Dress Size', 'value' => 'L'],
                    ['name' => 'Dress Size', 'value' => 'XL'],
                    ['name' => 'Color', 'value' => 'Red'],
                ]),
            ],
            [
                'name'              => 'France Away Jersey 2026',
                'description'       => 'France 2026 away jersey in an elegant white colourway with blue and red accents. Features the FFF rooster crest and is crafted from FlyEase technology fabric for all-day comfort.',
                'short_description' => 'France 2026 away jersey in white with FFF rooster crest.',
                'price'             => 1280.00,
                'sale_price'        => 1080.00,
                'SKU'               => 'NIKE-FRA-035',
                'stock'             => 32,
                'status'            => true,
                'category_id'       => 8,
                'sub_category'      => 'Football Jersey',
                'brand'             => 'Nike',
                'tax'               => 10.00,
                'discount'          => 15.63,
                'unit'              => 'pcs',
                'stock_status'      => 'in-stock',
                'featured'          => false,
                'best_seller'       => false,
                'organic'           => false,
                'new_arrival'       => true,
                'meta_title'        => 'France Away Jersey 2026',
                'meta_description'  => 'France 2026 away jersey in white with FFF rooster crest.',
                'meta_keywords'     => 'France, Football Jersey, 2026',
                'attributes'        => json_encode([
                    ['name' => 'Dress Size', 'value' => 'S'],
                    ['name' => 'Dress Size', 'value' => 'M'],
                    ['name' => 'Dress Size', 'value' => 'L'],
                    ['name' => 'Dress Size', 'value' => 'XL'],
                    ['name' => 'Dress Size', 'value' => 'XXL'],
                    ['name' => 'Color', 'value' => 'White'],
                ]),
            ],
        ];

        foreach ($products as $product) {
            $slug = Str::slug($product['name']) . '-' . substr(uniqid(), -8);
            DB::table('products')->insert(array_merge($product, [
                'slug'       => $slug,
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
